In [ ]:
import os
os.chdir("C:/Users/Kali Prasad/Desktop/dataset/dataset")

In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dropout

Using TensorFlow backend.
C:\Users\Kali Prasad\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Kali Prasad\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Kali Prasad\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Kali Prasad\anaconda3\lib\site-packages\tensorflow\py

In [3]:
#Intialize the model
model=Sequential()

In [4]:
# Add Convolution Layer
model.add(Convolution2D(32,(3,3),input_shape=(224,224,3),activation="relu"))

In [5]:
model.add(Convolution2D(64,(3,3),input_shape=(224,224,3),activation="relu"))

In [6]:
model.add(MaxPooling2D(pool_size = (2, 2)))

In [7]:
model.add(Dropout(0.2))

In [8]:
#Add Flattening Layer
model.add(Flatten())

In [9]:
#Add Hidden Layer
model.add(Dense(init="uniform",activation="relu",output_dim=128))

C:\Users\Kali Prasad\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  


In [10]:
#Add Output layer
model.add(Dense(init="uniform",activation="softmax",output_dim=5))

C:\Users\Kali Prasad\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=5, kernel_initializer="uniform")`
  


In [11]:
#Compile the model
model.compile(loss='categorical_crossentropy',optimizer="adam",metrics=["accuracy"])

In [14]:
print(x_train.class_indices)

{'actinic keratosis': 0, 'melanoma': 1, 'psorasis': 2, 'seborrheic keratosis': 3, 'vascular lesion': 4}


In [15]:
model.fit_generator(x_train,
                         steps_per_epoch = 200,
                         epochs = 7,
                         validation_data = x_test,
                         validation_steps = 63)


Epoch 1/7
200/200 [==============================] - 884s 4s/step - loss: 1.3744 - accuracy: 0.5251 - val_loss: 0.7202 - val_accuracy: 0.7970
Epoch 2/7
200/200 [==============================] - 915s 5s/step - loss: 0.7883 - accuracy: 0.7103 - val_loss: 0.4984 - val_accuracy: 0.8135
Epoch 3/7
200/200 [==============================] - 911s 5s/step - loss: 0.6195 - accuracy: 0.7709 - val_loss: 0.8286 - val_accuracy: 0.8498
Epoch 4/7
200/200 [==============================] - 979s 5s/step - loss: 0.6432 - accuracy: 0.7467 - val_loss: 0.4177 - val_accuracy: 0.7625
Epoch 5/7
200/200 [==============================] - 1113s 6s/step - loss: 0.5696 - accuracy: 0.7977 - val_loss: 0.5347 - val_accuracy: 0.8548
Epoch 6/7
200/200 [==============================] - 1245s 6s/step - loss: 0.6403 - accuracy: 0.7673 - val_loss: 0.1151 - val_accuracy: 0.9076
Epoch 7/7
200/200 [==============================] - 994s 5s/step - loss: 0.4496 - accuracy: 0.8333 - val_loss: 0.4489 - val_accuracy: 0.8571


In [16]:
model.save("skindisease.h5")

In [17]:
from keras.models import load_model
import numpy as np
import cv2

In [19]:

model = load_model('skindisease.h5')
# model.compile(loss='categorical_crossentropy',
#                       optimizer='adam',
#                       metrics=['accuracy'])

from skimage.transform import resize

def detect(frame):
    try:
        img = resize(frame,(224,224))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(prediction)
    except AttributeError:
        print("shape not found")


In [57]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/psorasis/p10.jpg")
data = detect(frame)

[[6.5145381e-05 6.6739056e-05 9.8090440e-01 1.8962050e-02 1.6921389e-06]]
[2]


In [74]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/melanoma/g2.jpg")
data = detect(frame)

[[3.0803112e-03 7.1157259e-01 1.4858876e-02 2.7000338e-01 4.8487604e-04]]
[1]


In [22]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/seborrheic keratosis/ISIC_0000142 - Copy.jpg")
data = detect(frame)

[[1.0426810e-13 1.4608606e-06 8.0050341e-12 9.9999857e-01 4.9922977e-17]]
[3]


In [43]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/actinic keratosis/ISIC_0026040.jpg")
data = detect(frame)

[[8.86732161e-01 6.30198047e-02 1.27860075e-02 2.40115536e-04
  3.72218452e-02]]
[0]


In [59]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/vascular lesion/ISIC_0030722.jpg")
data = detect(frame)

[[1.6150437e-16 2.4570873e-20 4.3352701e-18 2.5397133e-14 1.0000000e+00]]
[4]
