In [6]:
import os
os.chdir("C:/Users/Kali Prasad/Desktop/skin diseases flask/skin-disease-flask")

In [7]:
from keras.models import load_model
import numpy as np
import cv2

In [8]:

model = load_model('skindisease.h5')

from skimage.transform import resize

def detect(frame):
    try:
        img = resize(frame,(224,224))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(prediction)
    except AttributeError:
        print("shape not found")


In [9]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/psorasis/p10.jpg")
data = detect(frame)

[[6.5145381e-05 6.6739056e-05 9.8090440e-01 1.8962050e-02 1.6921389e-06]]
[2]


In [10]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/melanoma/g4.jpg")
data = detect(frame)

[[0.2764241  0.62060577 0.03120937 0.04426359 0.02749719]]
[1]


In [11]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/seborrheic keratosis/ISIC_0000142.jpg")
data = detect(frame)

[[1.0426810e-13 1.4608606e-06 8.0050341e-12 9.9999857e-01 4.9922977e-17]]
[3]


In [12]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/actinic keratosis/ISIC_0026040.jpg")
data = detect(frame)

[[8.86732161e-01 6.30198047e-02 1.27860075e-02 2.40115536e-04
  3.72218452e-02]]
[0]


In [13]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/vascular lesion/ISIC_0030722.jpg")
data = detect(frame)

[[1.6150437e-16 2.4570873e-20 4.3352701e-18 2.5397133e-14 1.0000000e+00]]
[4]
