In [ ]:
import os
os.chdir("C:/Users/Kali Prasad/Desktop/dataset/dataset")

In [43]:

model = load_model('skindisease1.h5')

from skimage.transform import resize

def detect(frame):
    try:
        img = resize(frame,(224,224))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(prediction)
    except AttributeError:
        print("shape not found")


In [44]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/psorasis/p10.jpg")
data = detect(frame)

[[9.9297453e-05 3.0656716e-05 9.9944168e-01 4.2821458e-04 1.1795704e-07]]
[2]


In [49]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/melanoma/g4.jpg")
data = detect(frame)

[[0.2370628  0.2590986  0.17670603 0.1805341  0.14659846]]
[1]


In [50]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/seborrheic keratosis/ISIC_0000142.jpg")
data = detect(frame)

[[5.1814737e-14 3.7270278e-05 7.6651757e-10 9.9996269e-01 3.7929100e-17]]
[3]


In [47]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/actinic keratosis/ISIC_0026040.jpg")
data = detect(frame)

[[0.33556792 0.1726142  0.22061227 0.09388291 0.17732263]]
[0]


In [48]:
frame=cv2.imread("C:/Users/Kali Prasad/Desktop/dataset/dataset/Train/vascular lesion/ISIC_0030722.jpg")
data = detect(frame)

[[1.5015107e-14 4.5873346e-17 2.1092765e-16 1.8467455e-10 1.0000000e+00]]
[4]
